In [2]:
from scipy import sparse
import numpy as np

In [5]:
s = np.array([[1, 2], [3, 4]])

In [7]:
print("s: \n{}".format(s))

s: 
[[1 2]
 [3 4]]


In [9]:
eye = np.eye(4)
print("eye: \n{}".format(eye))

eye: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
sparse_matrix = sparse.csr_matrix(eye)
print("\nSciPy sparse CSR matrix:\n{}".format(sparse_matrix))


SciPy sparse CSR matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [14]:
sparse_coo = sparse.coo_matrix(eye)
print("\nSciPy sparse COO matrix:\n{}".format(sparse_coo))


SciPy sparse COO matrix:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [17]:
row_indices = np.arange(4)
column_indices = np.arange(4)
# numpy.arange([start, ]stop, [step, ]dtype = None)
print("\nrow_indices:\n{}".format(row_indices))


row_indices:
[0 1 2 3]


In [22]:
data = np.ones(4)
eye_coo = sparse.coo_matrix((data,(row_indices, column_indices)))
print("\nCOO representation:\n{}".format(eye_coo))


COO representation:
  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0


In [24]:
import pandas as pd
from IPython import display

In [25]:
data = {'Name' : ["John", "Anna", "Peter", "Linda"],
              'Location' : ["New York", "Paris", "Berlin", "London"],
              'Age' : [24, 13, 53, 33]
       }

In [26]:
data_pandas = pd.DataFrame(data)

In [35]:
import sys
print("Python version: {}".format(sys.version))

Python version: 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 12:04:33) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]


In [37]:
import pandas as pd
print("pandas version: {}".format(pd.__version__))

pandas version: 0.22.0


In [38]:
import IPython
print("IPython version: {}".format(IPython.__version__))

IPython version: 6.2.1


In [39]:
import sklearn
print("scikit-learn version: {}".format(sklearn.__version__))

scikit-learn version: 0.19.1
